### ISSUE TITLE
Exported GPX files use local time rather than UTC.

### ISSUE THREAD

**Issue by junkyardsparkle** [emdete/tabulae#1]
From http://www.topografix.com/gpx/1/1/gpx.xsd :

"Creation/modification timestamp for element. Date and time in are in Univeral Coordinated Time (UTC), not local time! Conforms to ISO 8601 specification for date/time representation. Fractional seconds are allowed for millisecond timing in tracklogs. "

However, exported GPX files in tabulae (and Rmaps) use local time.

Very happy to see this project revived, by the way! :D

**Comment by junkyardsparkle** [comment]
Although it appears that it _thinks_ that it's using UTC, since it uses the "Z" timezone designation in the timestamps...

**Comment by emdete** [comment]
This one is fixed in 10.0.2 (will be released soon)
