### ISSUE TITLE
Not usable on CM 10.1 / Android 4.2

### ISSUE THREAD

**Issue by gjedeer** [emdete/tabulae#11]
I loved RMaps so I was very excited to learn you're continuing the development (found out about it in a Conversations thread).

Installed 1.0.10 from F-Droid and this is what it looks like:

![screenshot_2015-12-07-20-04-19](https://cloud.githubusercontent.com/assets/315648/11636871/a31a354c-9d1e-11e5-860f-5dbce78c0eee.png)

Settings:

![screenshot_2015-12-07-20-04-51](https://cloud.githubusercontent.com/assets/315648/11636872/a31c34f0-9d1e-11e5-87b8-1c555b675d5c.png)

Everything is underlined and the dashboard is taking almost half of screen resolution. That, plus status bar, and there's just 1/4 of screen left for the map.

**Comment by emdete** [comment]
i am currently doing a complete rewrite of the app. please stay tuned. i hope i will re implement all the features that made you love rmaps. :)

**Comment by gjedeer** [comment]
\o/ Glad to hear this!
