### ISSUE TITLE
add support for mapsforge library?

### ISSUE THREAD

**Issue by ghost** [emdete/tabulae#7]
http://wiki.openstreetmap.org/wiki/Mapsforge  is a java library to render offline vector maps. Quite a few maps are available for download  ( http://openandromaps.org ) but the most popular apps using the library are closed source.

**Comment by emdete** [comment]
i really love vector maps and thought of doing so. this is a good pointer to start looking into the topic. currently i am in rewriting the whole app so i will consider the mapsforge library, thank you for the pointer!
