### ISSUE TITLE
Enhancement: include HH:MM:SS time display.

### ISSUE THREAD

**Issue by junkyardsparkle** [emdete/tabulae#9]
I often use the tracks recorded with tabulae for adding coordinates to photos from a non-phone camera. Doing this accurately requires either keeping the camera clock synchronized with the phone or, alternately, taking a photo of the phone time display for use in calculating the offset that needs to be applied to the EXIF time in the image files. For either purpose, having a time display including seconds somewhere in tabulae would be convenient, particularly since I'm not aware of any open source apps that display this. An option to have a large clock display upon starting a track would also serve as a reminder to set the clock or take the photo. I realize this might not be the most widely used feature, but hope it could be trivial in terms of added bloat and effort (not sure if that's the case). Thanks for considering.

**Comment by emdete** [comment]
i will considere to add it to the dashboard. it will trigger an event every second but that shouldn't harm the battery much. thank your for the suggestion. 

btw: if you happen to have some time you can join the alpha testing of Tabulae2, development is currently slow but the app is evolving. you can join here: https://play.google.com/apps/testing/org.pyneo.tabulae

be aware that this is just showing maps and the dashboard, allows scrolling, zooming & auto-follow. huge improvement are the vectormaps which are currently not downloaded automatically, so you wont see them (other maps/sat-pics are provided as well).
